# Generated by Django 3.2 on 2021-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='outstanding_dues',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
