# Generated by Django 3.2 on 2021-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_outstanding_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='duration_of_bill',
            field=models.CharField(choices=[('1 Month', 'Month1'), ('3 Months', 'Month3'), ('6 Months', 'Month6')], default='1 month', max_length=20),
            preserve_default=False,
        ),
    ]
